name: greet the repo users

on: workflow_dispatch

jobs:
  greetings:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: run the script in the repo
      run: |
        chmod +x test.sh
        ./test.sh
